services:
  php:
    container_name: php-fpm
    build:
      context: .
      dockerfile: ./etc/docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./public:/var/www/html/public:rw
      - ./etc/docker/php/host/path/conf.d/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_NAME: myDataBaseName
      DATABASE_USER: root
      DATABASE_PASSWORD: root

  nginx:
    container_name: nginx-container
    build:
      context: .
      dockerfile: ./etc/docker/nginx/Dockerfile
    restart: unless-stopped
    volumes:
      #- ./src:/var/www/html
      - ./public:/var/www/html/public:rw
      - ./etc/docker/nginx/host/path/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/docker/nginx/host/path/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php
      - db
    networks:
      - app-network

  db:
    image: mariadb
    container_name: mariadb-container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: myDataBaseName
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - database_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  database_data: {}
